#!/bin/bash
set -eu -o pipefail

if [[ $EUID -ne 0 ]]; then
  echo "$0 needs to be run as root"
  exit 1
fi

TARGET=$(mktemp -d /tmp/runc_XXXXXXXXXX)
SKIP=$(awk '/^__TARFILE_STARTS_HERE__/ { print NR + 1; exit 0; }' "$0")

tail -n "+$SKIP" "$0" | tar -C "$TARGET" -xz

cd "$TARGET" && ./runc container.json
rm -rf "$TARGET"
exit 0

__TARFILE_STARTS_HERE__
